# Generated by Django 3.2 on 2021-05-01 23:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
