# Generated by Django 3.2 on 2021-05-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun', '0003_run_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='character',
            field=models.CharField(choices=[('commando', 'Commando'), ('huntress', 'Huntress'), ('bandit', 'Bandit'), ('mult', 'Mult'), ('engineer', 'Engineer'), ('artificer', 'Artificer'), ('mercenary', 'Mercenary'), ('rex', 'Rex'), ('loader', 'Loader'), ('acrid', 'Acrid'), ('captain', 'Captain')], default='engineer', max_length=30),
        ),
    ]
